CREATE TABLE IF NOT EXISTS ACTIVE_CHAT (
 ID SERIAL PRIMARY KEY NOT NULL,
 CHAT_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS INCOME (
 ID SERIAL PRIMARY KEY NOT NULL,
 CHAT_ID INTEGER NOT NULL,
 INCOME INTEGER
);

CREATE TABLE IF NOT EXISTS SPEND (
 ID SERIAL PRIMARY KEY NOT NULL,
 CHAT_ID INTEGER NOT NULL,
 SPEND INTEGER
);